version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9000:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      VIRTUAL_HOST: 'pi.farlee'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=Etc/UTC
    ports:
        - "9001:8000" # HTTP
        - "8443:8443" # HTTPS
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./crafty/backups:/crafty/backups
        - ./crafty/logs:/crafty/logs
        - ./crafty/servers:/crafty/servers
        - ./crafty/config:/crafty/app/config
        - ./crafty/import:/crafty/import